require("CVAS_1Tweakers");
--Vanilla
TweakItemCVAS("Base.Bullets9mmBox","DisplayCategory","Ammo");
TweakItemCVAS("Base.9mmClip","DisplayCategory","Ammo");
TweakItemCVAS("Base.Bullets45Box","DisplayCategory","Ammo");
TweakItemCVAS("Base.45Clip","DisplayCategory","Ammo");
TweakItemCVAS("Base.Bullets44Box","DisplayCategory","Ammo");
TweakItemCVAS("Base.44Clip","DisplayCategory","Ammo");
TweakItemCVAS("Base.Bullets38Box","DisplayCategory","Ammo");
TweakItemCVAS("Base.ShotgunShells","DisplayCategory","Ammo");
TweakItemCVAS("Base.ShotgunShellsBox","DisplayCategory","Ammo");
TweakItemCVAS("Base.223Box","DisplayCategory","Ammo");
TweakItemCVAS("Base.223Clip","DisplayCategory","Ammo");
TweakItemCVAS("Base.308Box","DisplayCategory","Ammo");
TweakItemCVAS("Base.308Clip","DisplayCategory","Ammo");
TweakItemCVAS("Base.556Box","DisplayCategory","Ammo");
TweakItemCVAS("Base.556Clip","DisplayCategory","Ammo");
TweakItemCVAS("Base.M14Clip","DisplayCategory","Ammo");